apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cats-app
  labels:
    app: my-cats-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-cats-app
  template:
    metadata:
      labels:
        app: my-cats-app
    spec:
      containers:
        - name: my-cats-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
